### PR TITLE
Fix load_schema_and_validate()

### PR DESCRIPTION
**Pull request by eshiroma**
/gcbrun

### CODE REVIEW

**Comment by gibbleyg** [comment]
While you're at it could you change this line to say something like "END OF WARNING"?

https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/f6027496895acf7c6a179af86700768d4ece35bc/scripts/verify#L119

In the past I was confused and thought the stack trace here was the reason for verification failure.

**Comment by gibbleyg** [comment]
Looks like there was already a PR for this as well https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/526

**Comment by eshiroma** [comment]
Added `END OF WARNING`.

Ah - we should review issue/PR monitoring with ops.

/gcbrun

**Comment by eshiroma** [comment]
For some reason, the cluster cleanup is failing (even on retry). Since all test steps (including `verify`) are successful, pushing.

**Comment by eshiroma** [comment]
Nevermind - it finally succeeded. Possibly because I manually deleted the cluster.

**Pull request merged**
